name: flutter_drawable_mipmap_example
description: Demonstrates how to use the flutter_drawable_mipmap plugin.
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_drawable_mipmap:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true